# Copyright 2014 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""add port timestamp revision

Revision ID: 238cf36dab26
Revises: juno
Create Date: 2014-11-27 17:04:05.835703

"""

# revision identifiers, used by Alembic.
revision = '238cf36dab26'
down_revision = 'juno'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ports', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('ports', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'updated_at')
    op.drop_column('ports', 'created_at')
    ### end Alembic commands ###
