- job:
    name: tricircle-functional-python3
    parent: legacy-dsvm-base
    run: playbooks/tricircle-dsvm-functional/run.yaml
    post-run: playbooks/tricircle-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/tricircle
      - openstack/neutron
      - openstack/networking-sfc
    vars:
      devstack_localrc:
        USE_PYTHON3: true

- job:
    name: tricircle-multiregion
    parent: legacy-dsvm-base-multinode
    run: playbooks/tricircle-dsvm-multiregion/run.yaml
    post-run: playbooks/tricircle-dsvm-multiregion/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/networking-sfc
      - openstack/tricircle

- job:
    name: tricircle-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    required-projects:
      - openstack/neutron
      - openstack/networking-sfc

- job:
    name: tricircle-tox-cover
    parent: openstack-tox-cover
    required-projects:
      - openstack/neutron
      - openstack/networking-sfc


- project:
    templates:
      - openstack-python3-ussuri-jobs-neutron
      - openstack-python3-ussuri-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tricircle-tox-cover
        - tricircle-tox-lower-constraints
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - openstack/networking-sfc
        - openstack-tox-py36:
            required-projects:
              - openstack/neutron
              - openstack/networking-sfc
        - tricircle-functional-python3
        - tricircle-multiregion
    gate:
      jobs:
        - tricircle-tox-lower-constraints
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
              - openstack/networking-sfc
        - openstack-tox-py36:
            required-projects:
              - openstack/neutron
              - openstack/networking-sfc
        - tricircle-multiregion
